"""empty message

Revision ID: 2e7bb99fb899
Revises: 38f439764817
Create Date: 2023-10-14 19:42:08.489827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7bb99fb899'
down_revision = '38f439764817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=150), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('looking_for_talent')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('looking_for_venue')

    # ### end Alembic commands ###
